alias -- console='javaws -J-Djava.security.properties=/home/cpayne/.config/icedtea-web/disabled_tls.properties'
alias -- gs='git status'
alias -- l='ls -alh'
alias -- ll='ls -l'
alias -- ls='ls --color=tty'
alias -- m='ssh cpayne.nine.ch'
alias -- mo='mosh --no-init cpayne.nine.ch'
alias -- cz41='ssh cpayne-cz41.nine.ch'
alias -- cz41m='mosh --no-init cpayne-cz41.nine.ch'
alias -- cz41e='et cpayne-cz41.nine.ch'
alias -- cz42='ssh cpayne-cz42.nine.ch'
alias -- cz42m='mosh --no-init cpayne-cz42.nine.ch'
alias -- cz42e='et cpayne-cz42.nine.ch'
alias -- es34='ssh cpayne-es34.nine.ch'
alias -- es34m='mosh --no-init cpayne-es34.nine.ch'
alias -- es34e='et cpayne-es34.nine.ch'
alias -- myip='dig +short myip.opendns.com @resolver1.opendns.com'
alias -- panel-reset='gnome-panel -r &> /dev/null &'
